name: Deploy
on:
  push:
    branches:
      - main

jobs:
  vercel:
    runs-on: ubuntu-latest
    name: Deploy to Vercel
    concurrency:
      group: 'deploy-vercel'
      cancel-in-progress: false
    steps:
      - uses: actions/checkout@v4
      - name: Deploy to Vercel
        env:
          VERCEL_JSON: ${{ secrets.VERCEL_JSON }}
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: |
          mkdir -p .vercel
          echo $VERCEL_JSON > .vercel/project.json
          npx vercel --prod --yes --token $VERCEL_TOKEN
